-- HOW MANY ORDERS WERE PLACED IN EACH YEAR?

SELECT 
YEAR(OrderDate) AS Year,
COUNT(*) AS No_Of_Years
FROM Sales.Orders 
GROUP BY YEAR(OrderDate)
ORDER BY COUNT(*) DESC

-- HOW MANY ORDERS WERE PLACED IN EACH MONTH?

SELECT 
DATENAME(MONTH, OrderDate) AS MONTH,
COUNT(*) AS No_Of_MOnths
FROM Sales.Orders 
GROUP BY DATENAME(MONTH, OrderDate)
ORDER BY COUNT(*) DESC
