-- FIND THE TOTAL SALES FOR EACH PRODUCT 
-- ADDITIONALLY PROVIDE DETAILS SUCH ORDER ID, ORDER DATE

-- USE WINDOW FUNCTIONS

SELECT
OrderID,
OrderDate,
ProductID,
SUM(Sales) OVER(PARTITION BY(ProductID)) AS TotalSales
FROM Sales.Orders