-- FIND THE LOWEST AND HIGHEST SALES FOR EACH PRODUCT

SELECT
	OrderID,
	Sales,
	ProductID,
	FIRST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales) AS LowestSale,
	LAST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS HighestSale
FROM Sales.Orders
