-- SORT THE SCORE OF THE CUSTOMER FROM LOWEST TO HIGHEST 
-- WHILE NULL SHOULD BE APPERED AT THE LAST ROW

SELECT
CustomerID,
Score
FROM Sales.Customers
ORDER BY CASE WHEN Score IS NULL THEN 1 ELSE 0 END, Score;