-- IDENTIFY DUPLICATE ROWS IN THE TABLE ORDERSARCHIVE
-- AND RETURN A CLEAN RESULT WITHOUT ANY DUPLICATES

-- CLEAN DATA
SELECT
*
	FROM 
	(
	SELECT
	ROW_NUMBER() OVER(PARTITION BY OrderID ORDER BY CreationTime DESC) AS rn,
	*
	FROM Sales.OrdersArchive
) t
WHERE rn = 1

-- DUPLICATED DATA
SELECT
*
	FROM 
	(
	SELECT
	ROW_NUMBER() OVER(PARTITION BY OrderID ORDER BY CreationTime DESC) AS rn,
	*
	FROM Sales.OrdersArchive
) t
WHERE rn > 1
