-- CALCULATE THE MOVING AVERAGE OF SALES 
-- FOR EACH PRODUCT OVER TIME
-- ALSO BY INCLUDING ONLY NEXT ORDER

SELECT
	OrderID, 
	Sales, 
	ProductID,
	OrderDate,
	AVG(Sales) OVER(PARTITION BY ProductID) AS AvgByProduct,
	AVG(Sales) OVER(PARTITION BY ProductID ORDER BY OrderDate) AS MovingAvg,
	AVG(Sales) OVER(PARTITION BY ProductID ORDER BY OrderDate ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) AS RollingAvg
FROM Sales.Orders