-- COUNT HOW MANY TIMES EACH CUSTOMER HAS MADE AN ORDER WITH SALES GREATER THAN 30

SELECT 
CustomerID,
SUM(
	CASE
		WHEN Sales > 30 THEN 1
		ELSE 0
	END
) AS TotalSales
FROM Sales.Orders
GROUP BY CustomerID