-- GENERATE A REPORT SHOWING THE TOTAL SALES FOR EACH CATEGORY:
-- HIGH: IF THE SALE IS HIGHER THAN 50
-- MEDIUM: IF THE SALE IS BETWEEN 20 AND 50
-- LOW: IF THE SALE EQUAL OR LOWER THAN 20
-- SORT THE RESULT FROM LOWEST TO HIGHEST

SELECT
Category,
SUM(Sales) AS TotalSales
FROM
(
	SELECT
	OrderID, Sales,
	CASE
		WHEN Sales > 50 THEN 'High'
		WHEN Sales > 20 THEN 'Medium'
		ELSE 'Low'
	END Category
	FROM Sales.Orders
)t
GROUP BY Category
