-- RANK THE ORDERS BASED ON THEIR SALES FROM HIGHEST TO LOWEST

SELECT
	ROW_NUMBER() OVER(ORDER BY Sales DESC) AS SalesRank_Rows,
	RANK() OVER(ORDER BY Sales DESC) AS SalesRank,
	DENSE_RANK() OVER(ORDER BY Sales DESC) AS DenseRankOnSales,
	OrderID, ProductID, Sales
FROM Sales.Orders