-- FIND OUT THE EMPLOYEES WHO ARE ABOUT TO RETIRED

SELECT
EmployeeID,
FirstName,
BirthDate,
DATEDIFF(YEAR, BirthDate, GETDATE()) AS AGE
FROM Sales.Employees
WHERE DATEDIFF(YEAR, BirthDate, GETDATE()) > 50